[package]
name = "dusage"
version = "0.2.0"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "💾 A command line disk usage information tool.\n\nDisk usage percentage is displayed in a bar with the inode usage percentage as background."
categories = ["command-line-utilities", "filesystem"]
keywords = ["disk", "disk-usage"]
repository = "https://github.com/mihaigalos/dusage"
license = "MIT"

[dependencies]
byte-unit = "4.0.13"
clap = "2.33.2"
colored = "2"
nix = "0.23.0"
