[package]
name = "dusage"
version = "0.3.0"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "💾 A command line disk usage information tool: disk usage (foreground), inodes (background)."
categories = ["command-line-utilities", "filesystem"]
keywords = ["disk", "disk-usage"]
repository = "https://github.com/mihaigalos/dusage"
license = "MIT"

[dependencies]
autoclap = "0.2.2"
byte-unit = "4.0.13"
clap = { version = "3.1.8", features = ["cargo"] }
colored = "2"
nix = "0.23.0"
