[package]
name = "dusage"
version = "0.3.3"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "💾 A command line disk usage information tool: disk usage (foreground), inodes (background)."
categories = ["command-line-utilities", "filesystem"]
keywords = ["disk", "disk-usage"]
repository = "https://github.com/mihaigalos/dusage"
license = "MIT"

[dependencies]
autoclap = "0.3.3"
byte-unit = "4.0.14"
clap = { version = "4.0.12", features = ["cargo", "string"] }
colored = "2"
nix = "0.25.0"
